mqtt:
  enabled: false

detectors:
  #  cpu1:
  #    type: cpu
  #    num_threads: 3
  coral:
    type: edgetpu
    device: usb

cameras:
  attic_4k:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:tnh774HZ@192.168.70.02:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        - path: rtsp://admin:tnh774HZ@192.168.70.02:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
    detect:
      enabled: true
      width: 704
      height: 408
      fps: 5
    snapshots:
      enabled: true
    record:
      enabled: true
      retain:
        days: 2
        mode: all
      events:
        retain:
          default: 100
          mode: active_objects
    motion:
      mask: 1,0,1,0.12,0.796,0.119,0.795,0
  workshop:
    enabled: true
    ffmpeg:
      inputs:
        - path:
            rtsp://admin:tnh774HZ@192.168.70.01:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
            - record
        - path: rtsp://admin:tnh774HZ@192.168.70.01:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    detect:
      enabled: true
      width: 704
      height: 408
      fps: 5
    # objects:
    #   track:
    #     - person
    #     - dog
    #     - car
    #     - mouse
    #   filters:
    #     person:
    #       threshold: 0.8
    #       min_area: 5000
    #       max_area: 100000
    #     car:
    #       threshold: 0.8
    #       min_area: 5000
    #       max_area: 100000
    snapshots:
      enabled: true
    record:
      enabled: true
      retain:
        days: 2
        mode: all
      events:
        retain:
          default: 100
          mode: active_objects

    zones: {}
    motion:
      mask: 0.571,0.005,0.574,0.111,0.985,0.129,0.976,0.003
    review:
      detections: {}
version: 0.14
